### ISSUE TITLE
testMemory.sh calling setMemoryUsage.js instead of objectMemoryUsage.js for "Testing with Object"

### ISSUE THREAD

**Issue by cervaens** [anvaka/set-vs-object#6]
Hi anvaka,

Donno if you've noticed the above.
I was doing my own benchmark and by using Set instead of a js object the heap memory was greatly (hugely) improved, so I tried to see why your testMemory.sh results were very similar.

cheers,
nuno

**Comment by anvaka** [comment]
Thanks for the call out!
